version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run test
          name: Build package
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  default:
    jobs:
      - test
